/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppRoutersRouteImport } from './routes/_app/routers'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppLoyaltyRouteImport } from './routes/_app/loyalty'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppClientsStaticRouteImport } from './routes/_app/clients.static'
import { Route as AppClientsPppoeRouteImport } from './routes/_app/clients.pppoe'
import { Route as AppClientsHotspotRouteImport } from './routes/_app/clients.hotspot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutersRoute = AppRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsStaticRoute = AppClientsStaticRouteImport.update({
  id: '/clients/static',
  path: '/clients/static',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsPppoeRoute = AppClientsPppoeRouteImport.update({
  id: '/clients/pppoe',
  path: '/clients/pppoe',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsHotspotRoute = AppClientsHotspotRouteImport.update({
  id: '/clients/hotspot',
  path: '/clients/hotspot',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$': typeof AppSplatRoute
  '/dashboard': typeof AppDashboardRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/plans': typeof AppPlansRoute
  '/routers': typeof AppRoutersRoute
  '/welcome': typeof AppWelcomeRoute
  '/clients/hotspot': typeof AppClientsHotspotRoute
  '/clients/pppoe': typeof AppClientsPppoeRoute
  '/clients/static': typeof AppClientsStaticRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$': typeof AppSplatRoute
  '/dashboard': typeof AppDashboardRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/plans': typeof AppPlansRoute
  '/routers': typeof AppRoutersRoute
  '/welcome': typeof AppWelcomeRoute
  '/clients/hotspot': typeof AppClientsHotspotRoute
  '/clients/pppoe': typeof AppClientsPppoeRoute
  '/clients/static': typeof AppClientsStaticRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/loyalty': typeof AppLoyaltyRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/routers': typeof AppRoutersRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/_app/clients/hotspot': typeof AppClientsHotspotRoute
  '/_app/clients/pppoe': typeof AppClientsPppoeRoute
  '/_app/clients/static': typeof AppClientsStaticRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$'
    | '/dashboard'
    | '/loyalty'
    | '/plans'
    | '/routers'
    | '/welcome'
    | '/clients/hotspot'
    | '/clients/pppoe'
    | '/clients/static'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$'
    | '/dashboard'
    | '/loyalty'
    | '/plans'
    | '/routers'
    | '/welcome'
    | '/clients/hotspot'
    | '/clients/pppoe'
    | '/clients/static'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/$'
    | '/_app/dashboard'
    | '/_app/loyalty'
    | '/_app/plans'
    | '/_app/routers'
    | '/_app/welcome'
    | '/_app/clients/hotspot'
    | '/_app/clients/pppoe'
    | '/_app/clients/static'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routers': {
      id: '/_app/routers'
      path: '/routers'
      fullPath: '/routers'
      preLoaderRoute: typeof AppRoutersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loyalty': {
      id: '/_app/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/static': {
      id: '/_app/clients/static'
      path: '/clients/static'
      fullPath: '/clients/static'
      preLoaderRoute: typeof AppClientsStaticRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/pppoe': {
      id: '/_app/clients/pppoe'
      path: '/clients/pppoe'
      fullPath: '/clients/pppoe'
      preLoaderRoute: typeof AppClientsPppoeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/hotspot': {
      id: '/_app/clients/hotspot'
      path: '/clients/hotspot'
      fullPath: '/clients/hotspot'
      preLoaderRoute: typeof AppClientsHotspotRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppPlansRoute: typeof AppPlansRoute
  AppRoutersRoute: typeof AppRoutersRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppClientsHotspotRoute: typeof AppClientsHotspotRoute
  AppClientsPppoeRoute: typeof AppClientsPppoeRoute
  AppClientsStaticRoute: typeof AppClientsStaticRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppPlansRoute: AppPlansRoute,
  AppRoutersRoute: AppRoutersRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppClientsHotspotRoute: AppClientsHotspotRoute,
  AppClientsPppoeRoute: AppClientsPppoeRoute,
  AppClientsStaticRoute: AppClientsStaticRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
