/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRoutersRouteImport } from './routes/_app/routers'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppLoyaltyRouteImport } from './routes/_app/loyalty'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsWhatsappRouteImport } from './routes/_app/settings.whatsapp'
import { Route as AppSettingsPppoeRouteImport } from './routes/_app/settings.pppoe'
import { Route as AppSettingsPaymentsRouteImport } from './routes/_app/settings.payments'
import { Route as AppSettingsPagebuilderRouteImport } from './routes/_app/settings.pagebuilder'
import { Route as AppSettingsHotspotRouteImport } from './routes/_app/settings.hotspot'
import { Route as AppSettingsEmailRouteImport } from './routes/_app/settings.email'
import { Route as AppSettingsDomainRouteImport } from './routes/_app/settings.domain'
import { Route as AppSettingsCommunicationsRouteImport } from './routes/_app/settings.communications'
import { Route as AppSettingsBrandingRouteImport } from './routes/_app/settings.branding'
import { Route as AppClientsStaticRouteImport } from './routes/_app/clients.static'
import { Route as AppClientsPppoeRouteImport } from './routes/_app/clients.pppoe'
import { Route as AppClientsHotspotRouteImport } from './routes/_app/clients.hotspot'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe.webhook'
import { Route as ApiPublicProvisionTokenRouteImport } from './routes/api/public/provision.$token'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa.callback'
import { Route as ApiPublicProvisionTokenCheckinRouteImport } from './routes/api/public/provision.$token.checkin'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutersRoute = AppRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsWhatsappRoute = AppSettingsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPppoeRoute = AppSettingsPppoeRouteImport.update({
  id: '/pppoe',
  path: '/pppoe',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPaymentsRoute = AppSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPagebuilderRoute = AppSettingsPagebuilderRouteImport.update({
  id: '/pagebuilder',
  path: '/pagebuilder',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsHotspotRoute = AppSettingsHotspotRouteImport.update({
  id: '/hotspot',
  path: '/hotspot',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsEmailRoute = AppSettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDomainRoute = AppSettingsDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCommunicationsRoute =
  AppSettingsCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsBrandingRoute = AppSettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppClientsStaticRoute = AppClientsStaticRouteImport.update({
  id: '/clients/static',
  path: '/clients/static',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsPppoeRoute = AppClientsPppoeRouteImport.update({
  id: '/clients/pppoe',
  path: '/clients/pppoe',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsHotspotRoute = AppClientsHotspotRouteImport.update({
  id: '/clients/hotspot',
  path: '/clients/hotspot',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProvisionTokenRoute = ApiPublicProvisionTokenRouteImport.update({
  id: '/api/public/provision/$token',
  path: '/api/public/provision/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProvisionTokenCheckinRoute =
  ApiPublicProvisionTokenCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => ApiPublicProvisionTokenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/rewards': typeof RewardsRoute
  '/$': typeof AppSplatRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/plans': typeof AppPlansRoute
  '/routers': typeof AppRoutersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/welcome': typeof AppWelcomeRoute
  '/clients/hotspot': typeof AppClientsHotspotRoute
  '/clients/pppoe': typeof AppClientsPppoeRoute
  '/clients/static': typeof AppClientsStaticRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/settings/communications': typeof AppSettingsCommunicationsRoute
  '/settings/domain': typeof AppSettingsDomainRoute
  '/settings/email': typeof AppSettingsEmailRoute
  '/settings/hotspot': typeof AppSettingsHotspotRoute
  '/settings/pagebuilder': typeof AppSettingsPagebuilderRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/settings/pppoe': typeof AppSettingsPppoeRoute
  '/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/provision/$token': typeof ApiPublicProvisionTokenRouteWithChildren
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/provision/$token/checkin': typeof ApiPublicProvisionTokenCheckinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/rewards': typeof RewardsRoute
  '/$': typeof AppSplatRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/plans': typeof AppPlansRoute
  '/routers': typeof AppRoutersRoute
  '/welcome': typeof AppWelcomeRoute
  '/clients/hotspot': typeof AppClientsHotspotRoute
  '/clients/pppoe': typeof AppClientsPppoeRoute
  '/clients/static': typeof AppClientsStaticRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/settings/communications': typeof AppSettingsCommunicationsRoute
  '/settings/domain': typeof AppSettingsDomainRoute
  '/settings/email': typeof AppSettingsEmailRoute
  '/settings/hotspot': typeof AppSettingsHotspotRoute
  '/settings/pagebuilder': typeof AppSettingsPagebuilderRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/settings/pppoe': typeof AppSettingsPppoeRoute
  '/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/provision/$token': typeof ApiPublicProvisionTokenRouteWithChildren
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/provision/$token/checkin': typeof ApiPublicProvisionTokenCheckinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/rewards': typeof RewardsRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/loyalty': typeof AppLoyaltyRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/routers': typeof AppRoutersRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/welcome': typeof AppWelcomeRoute
  '/_app/clients/hotspot': typeof AppClientsHotspotRoute
  '/_app/clients/pppoe': typeof AppClientsPppoeRoute
  '/_app/clients/static': typeof AppClientsStaticRoute
  '/_app/settings/branding': typeof AppSettingsBrandingRoute
  '/_app/settings/communications': typeof AppSettingsCommunicationsRoute
  '/_app/settings/domain': typeof AppSettingsDomainRoute
  '/_app/settings/email': typeof AppSettingsEmailRoute
  '/_app/settings/hotspot': typeof AppSettingsHotspotRoute
  '/_app/settings/pagebuilder': typeof AppSettingsPagebuilderRoute
  '/_app/settings/payments': typeof AppSettingsPaymentsRoute
  '/_app/settings/pppoe': typeof AppSettingsPppoeRoute
  '/_app/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/provision/$token': typeof ApiPublicProvisionTokenRouteWithChildren
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/provision/$token/checkin': typeof ApiPublicProvisionTokenCheckinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/rewards'
    | '/$'
    | '/billing'
    | '/dashboard'
    | '/loyalty'
    | '/plans'
    | '/routers'
    | '/settings'
    | '/welcome'
    | '/clients/hotspot'
    | '/clients/pppoe'
    | '/clients/static'
    | '/settings/branding'
    | '/settings/communications'
    | '/settings/domain'
    | '/settings/email'
    | '/settings/hotspot'
    | '/settings/pagebuilder'
    | '/settings/payments'
    | '/settings/pppoe'
    | '/settings/whatsapp'
    | '/settings/'
    | '/api/public/mpesa/callback'
    | '/api/public/provision/$token'
    | '/api/public/stripe/webhook'
    | '/api/public/provision/$token/checkin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/rewards'
    | '/$'
    | '/billing'
    | '/dashboard'
    | '/loyalty'
    | '/plans'
    | '/routers'
    | '/welcome'
    | '/clients/hotspot'
    | '/clients/pppoe'
    | '/clients/static'
    | '/settings/branding'
    | '/settings/communications'
    | '/settings/domain'
    | '/settings/email'
    | '/settings/hotspot'
    | '/settings/pagebuilder'
    | '/settings/payments'
    | '/settings/pppoe'
    | '/settings/whatsapp'
    | '/settings'
    | '/api/public/mpesa/callback'
    | '/api/public/provision/$token'
    | '/api/public/stripe/webhook'
    | '/api/public/provision/$token/checkin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/portal'
    | '/rewards'
    | '/_app/$'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/loyalty'
    | '/_app/plans'
    | '/_app/routers'
    | '/_app/settings'
    | '/_app/welcome'
    | '/_app/clients/hotspot'
    | '/_app/clients/pppoe'
    | '/_app/clients/static'
    | '/_app/settings/branding'
    | '/_app/settings/communications'
    | '/_app/settings/domain'
    | '/_app/settings/email'
    | '/_app/settings/hotspot'
    | '/_app/settings/pagebuilder'
    | '/_app/settings/payments'
    | '/_app/settings/pppoe'
    | '/_app/settings/whatsapp'
    | '/_app/settings/'
    | '/api/public/mpesa/callback'
    | '/api/public/provision/$token'
    | '/api/public/stripe/webhook'
    | '/api/public/provision/$token/checkin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
  RewardsRoute: typeof RewardsRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
  ApiPublicProvisionTokenRoute: typeof ApiPublicProvisionTokenRouteWithChildren
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routers': {
      id: '/_app/routers'
      path: '/routers'
      fullPath: '/routers'
      preLoaderRoute: typeof AppRoutersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loyalty': {
      id: '/_app/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/whatsapp': {
      id: '/_app/settings/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AppSettingsWhatsappRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/pppoe': {
      id: '/_app/settings/pppoe'
      path: '/pppoe'
      fullPath: '/settings/pppoe'
      preLoaderRoute: typeof AppSettingsPppoeRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/payments': {
      id: '/_app/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AppSettingsPaymentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/pagebuilder': {
      id: '/_app/settings/pagebuilder'
      path: '/pagebuilder'
      fullPath: '/settings/pagebuilder'
      preLoaderRoute: typeof AppSettingsPagebuilderRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/hotspot': {
      id: '/_app/settings/hotspot'
      path: '/hotspot'
      fullPath: '/settings/hotspot'
      preLoaderRoute: typeof AppSettingsHotspotRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/email': {
      id: '/_app/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AppSettingsEmailRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/domain': {
      id: '/_app/settings/domain'
      path: '/domain'
      fullPath: '/settings/domain'
      preLoaderRoute: typeof AppSettingsDomainRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/communications': {
      id: '/_app/settings/communications'
      path: '/communications'
      fullPath: '/settings/communications'
      preLoaderRoute: typeof AppSettingsCommunicationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/branding': {
      id: '/_app/settings/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AppSettingsBrandingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/clients/static': {
      id: '/_app/clients/static'
      path: '/clients/static'
      fullPath: '/clients/static'
      preLoaderRoute: typeof AppClientsStaticRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/pppoe': {
      id: '/_app/clients/pppoe'
      path: '/clients/pppoe'
      fullPath: '/clients/pppoe'
      preLoaderRoute: typeof AppClientsPppoeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/hotspot': {
      id: '/_app/clients/hotspot'
      path: '/clients/hotspot'
      fullPath: '/clients/hotspot'
      preLoaderRoute: typeof AppClientsHotspotRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provision/$token': {
      id: '/api/public/provision/$token'
      path: '/api/public/provision/$token'
      fullPath: '/api/public/provision/$token'
      preLoaderRoute: typeof ApiPublicProvisionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provision/$token/checkin': {
      id: '/api/public/provision/$token/checkin'
      path: '/checkin'
      fullPath: '/api/public/provision/$token/checkin'
      preLoaderRoute: typeof ApiPublicProvisionTokenCheckinRouteImport
      parentRoute: typeof ApiPublicProvisionTokenRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsBrandingRoute: typeof AppSettingsBrandingRoute
  AppSettingsCommunicationsRoute: typeof AppSettingsCommunicationsRoute
  AppSettingsDomainRoute: typeof AppSettingsDomainRoute
  AppSettingsEmailRoute: typeof AppSettingsEmailRoute
  AppSettingsHotspotRoute: typeof AppSettingsHotspotRoute
  AppSettingsPagebuilderRoute: typeof AppSettingsPagebuilderRoute
  AppSettingsPaymentsRoute: typeof AppSettingsPaymentsRoute
  AppSettingsPppoeRoute: typeof AppSettingsPppoeRoute
  AppSettingsWhatsappRoute: typeof AppSettingsWhatsappRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBrandingRoute: AppSettingsBrandingRoute,
  AppSettingsCommunicationsRoute: AppSettingsCommunicationsRoute,
  AppSettingsDomainRoute: AppSettingsDomainRoute,
  AppSettingsEmailRoute: AppSettingsEmailRoute,
  AppSettingsHotspotRoute: AppSettingsHotspotRoute,
  AppSettingsPagebuilderRoute: AppSettingsPagebuilderRoute,
  AppSettingsPaymentsRoute: AppSettingsPaymentsRoute,
  AppSettingsPppoeRoute: AppSettingsPppoeRoute,
  AppSettingsWhatsappRoute: AppSettingsWhatsappRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppPlansRoute: typeof AppPlansRoute
  AppRoutersRoute: typeof AppRoutersRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppClientsHotspotRoute: typeof AppClientsHotspotRoute
  AppClientsPppoeRoute: typeof AppClientsPppoeRoute
  AppClientsStaticRoute: typeof AppClientsStaticRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppPlansRoute: AppPlansRoute,
  AppRoutersRoute: AppRoutersRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWelcomeRoute: AppWelcomeRoute,
  AppClientsHotspotRoute: AppClientsHotspotRoute,
  AppClientsPppoeRoute: AppClientsPppoeRoute,
  AppClientsStaticRoute: AppClientsStaticRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiPublicProvisionTokenRouteChildren {
  ApiPublicProvisionTokenCheckinRoute: typeof ApiPublicProvisionTokenCheckinRoute
}

const ApiPublicProvisionTokenRouteChildren: ApiPublicProvisionTokenRouteChildren =
  {
    ApiPublicProvisionTokenCheckinRoute: ApiPublicProvisionTokenCheckinRoute,
  }

const ApiPublicProvisionTokenRouteWithChildren =
  ApiPublicProvisionTokenRoute._addFileChildren(
    ApiPublicProvisionTokenRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
  RewardsRoute: RewardsRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
  ApiPublicProvisionTokenRoute: ApiPublicProvisionTokenRouteWithChildren,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
